name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key.pub"
      - run: cat "$HOME/.ssh/key.pub"
      - run: chmod 600 "$HOME/.ssh/key.pub"
      - run: echo "194.67.104.28" > "$HOME/.ssh/known_hosts"
      - run: chmod 600 "$HOME/.ssh/known_hosts"
      # Deploy
      - run: rsync -e "ssh -i $HOME/.ssh/key.pub -o StrictHostKeyChecking=no" --archive --compress . corvus278@romylo-test.ru:/root/
